export interface GNItem {
  gnName: string;
  divisionalSecretariat: string;
}

export const gnList: GNItem[] = [
  { gnName: "Buddhangala", divisionalSecretariat: "Padaviya" },
  { gnName: "Elikibulagala", divisionalSecretariat: "Padaviya" },
  { gnName: "Abayapura", divisionalSecretariat: "Padaviya" },
  { gnName: "Maithreepura", divisionalSecretariat: "Padaviya" },
  { gnName: "Parakramapura", divisionalSecretariat: "Padaviya" },
  { gnName: "'B' yaya", divisionalSecretariat: "Padaviya" },
  { gnName: "Bisokotuwa", divisionalSecretariat: "Padaviya" },
  { gnName: "Sudharshanagama", divisionalSecretariat: "Padaviya" },
  { gnName: "Balayawewa", divisionalSecretariat: "Padaviya" },
  { gnName: "Mahasenpura", divisionalSecretariat: "Padaviya" },
  { gnName: "Urewa", divisionalSecretariat: "Padaviya" },
  { gnName: "Kubukwewa", divisionalSecretariat: "Padaviya" },
  { gnName: "Ruwanpura", divisionalSecretariat: "Padaviya" },
  { gnName: "Bogahawewa", divisionalSecretariat: "Padaviya" },
  { gnName: "Padaviya", divisionalSecretariat: "Padaviya" },
  { gnName: "Halmillawatiya", divisionalSecretariat: "Kebithigollewa" },
  { gnName: "Kanugahawewa", divisionalSecretariat: "Kebithigollewa" },
  { gnName: "Herathhalmillewa", divisionalSecretariat: "Kebithigollewa" },
  { gnName: "Bellankadawala", divisionalSecretariat: "Kebithigollewa" },
  { gnName: "Punchimudagama", divisionalSecretariat: "Kebithigollewa" },
  { gnName: "Wahalkada D 6", divisionalSecretariat: "Kebithigollewa" },
  { gnName: "Wahalkada D5", divisionalSecretariat: "Kebithigollewa" },
  { gnName: "Wahalkada D4", divisionalSecretariat: "Kebithigollewa" },
  { gnName: "Kahatagollewa", divisionalSecretariat: "Kebithigollewa" },
  { gnName: "Thammannawa", divisionalSecretariat: "Kebithigollewa" },
  { gnName: "Kunchuttuwa", divisionalSecretariat: "Kebithigollewa" },
  { gnName: "Galawewa", divisionalSecretariat: "Kebithigollewa" },
  { gnName: "Thiththagonewa", divisionalSecretariat: "Kebithigollewa" },
  { gnName: "Kurulugama", divisionalSecretariat: "Kebithigollewa" },
  { gnName: "Sinhala Etaweerawewa", divisionalSecretariat: "Kebithigollewa" },
  { gnName: "Ethalviddawewa", divisionalSecretariat: "Kebithigollewa" },
  { gnName: "Gonumeriyawa", divisionalSecretariat: "Kebithigollewa" },
  { gnName: "Kabithigollewa", divisionalSecretariat: "Kebithigollewa" },
  { gnName: "Ihala Usgollewa", divisionalSecretariat: "Kebithigollewa" },
  { gnName: "Aiyathigewewa", divisionalSecretariat: "Kebithigollewa" },
  { gnName: "Bandaraulpatha", divisionalSecretariat: "Kebithigollewa" },
  { gnName: "Kiriketuwawe", divisionalSecretariat: "Kebithigollewa" },
  { gnName: "Gonuhaddenawa", divisionalSecretariat: "Kebithigollewa" },
  { gnName: "Thibiriwewa", divisionalSecretariat: "Kebithigollewa" },
  { gnName: "Kirimatiyawa", divisionalSecretariat: "Kebithigollewa" },
  { gnName: "Watthewewa", divisionalSecretariat: "Kebithigollewa" },
  { gnName: "Prabodagama", divisionalSecretariat: "Medawachchiya" },
  { gnName: "Paranahalmillawa", divisionalSecretariat: "Medawachchiya" },
  { gnName: "Loolugaswewa", divisionalSecretariat: "Medawachchiya" },
  { gnName: "Puhudiula", divisionalSecretariat: "Medawachchiya" },
  { gnName: "Hirallugama", divisionalSecretariat: "Medawachchiya" },
  { gnName: "Athakada", divisionalSecretariat: "Medawachchiya" },
  { gnName: "Ataweeragollewa", divisionalSecretariat: "Medawachchiya" },
  { gnName: "Kadawathrambaya", divisionalSecretariat: "Medawachchiya" },
  { gnName: "Mahakumbukgollewa", divisionalSecretariat: "Medawachchiya" },
  { gnName: "Kidawarankulama", divisionalSecretariat: "Medawachchiya" },
  { gnName: "Anekattiya", divisionalSecretariat: "Medawachchiya" },
  { gnName: "Periyakulama", divisionalSecretariat: "Medawachchiya" },
  { gnName: "Poonawa", divisionalSecretariat: "Medawachchiya" },
  { gnName: "Isinbessagama", divisionalSecretariat: "Medawachchiya" },
  { gnName: "Mahadiulwewa", divisionalSecretariat: "Medawachchiya" },
  { gnName: "Kidagalegama", divisionalSecretariat: "Medawachchiya" },
  { gnName: "Moragoda", divisionalSecretariat: "Medawachchiya" },
  { gnName: "Unagasewewa", divisionalSecretariat: "Medawachchiya" },
  { gnName: "Kirigalwewa", divisionalSecretariat: "Medawachchiya" },
  { gnName: "Agunochchiya", divisionalSecretariat: "Medawachchiya" },
  { gnName: "Akirikanda", divisionalSecretariat: "Medawachchiya" },
  { gnName: "Rail Way Town", divisionalSecretariat: "Medawachchiya" },
  { gnName: "Kadawathgama", divisionalSecretariat: "Medawachchiya" },
  { gnName: "Kudakubukgollewa", divisionalSecretariat: "Medawachchiya" },
  { gnName: "Yakawewa", divisionalSecretariat: "Medawachchiya" },
  { gnName: "Thammennaelawaka", divisionalSecretariat: "Medawachchiya" },
  { gnName: "Pulelliya", divisionalSecretariat: "Medawachchiya" },
  { gnName: "Viralmuruppuwa", divisionalSecretariat: "Medawachchiya" },
  { gnName: "Walpola", divisionalSecretariat: "Medawachchiya" },
  { gnName: "Katuwela", divisionalSecretariat: "Medawachchiya" },
  { gnName: "Medawachchiya - West", divisionalSecretariat: "Medawachchiya" },
  { gnName: "Medawachchiya - East", divisionalSecretariat: "Medawachchiya" },
  { gnName: "Kanadaradiulwewa", divisionalSecretariat: "Medawachchiya" },
  { gnName: "Halabagaswewa", divisionalSecretariat: "Medawachchiya" },
  { gnName: "Sangilikanandarawa", divisionalSecretariat: "Medawachchiya" },
  { gnName: "Lindawewa", divisionalSecretariat: "Medawachchiya" },
  { gnName: "Karambankulama", divisionalSecretariat: "Medawachchiya" },
  { gnName: "Dematamalgama", divisionalSecretariat: "Mahavilachchiya" },
  { gnName: "Thantirimale", divisionalSecretariat: "Mahavilachchiya" },
  { gnName: "Nelumwila", divisionalSecretariat: "Mahavilachchiya" },
  { gnName: "Sadamaleliya", divisionalSecretariat: "Mahavilachchiya" },
  { gnName: "Thuppitiyawa", divisionalSecretariat: "Mahavilachchiya" },
  { gnName: "Athdathkalla", divisionalSecretariat: "Mahavilachchiya" },
  { gnName: "Randuwa", divisionalSecretariat: "Mahavilachchiya" },
  { gnName: "Palugaswewa", divisionalSecretariat: "Mahavilachchiya" },
  { gnName: "Mannaram Junction", divisionalSecretariat: "Mahavilachchiya" },
  { gnName: "Kudavilachchiya", divisionalSecretariat: "Mahavilachchiya" },
  { gnName: "Mahavilachchiya", divisionalSecretariat: "Mahavilachchiya" },
  { gnName: "Pemaduwa", divisionalSecretariat: "Mahavilachchiya" },
  { gnName: "Kiralpetiyawa", divisionalSecretariat: "Mahavilachchiya" },
  { gnName: "Navodagama", divisionalSecretariat: "Mahavilachchiya" },
  { gnName: "Oyamaduwa", divisionalSecretariat: "Mahavilachchiya" },
  { gnName: "Halabawewa", divisionalSecretariat: "Mahavilachchiya" },
  { gnName: "Dunumadalawa", divisionalSecretariat: "Mahavilachchiya" },
  { gnName: "Helarnbagaswewa", divisionalSecretariat: "Nuwaragam Palatha Central" },
  { gnName: "Asirikgama", divisionalSecretariat: "Nuwaragam Palatha Central" },
  { gnName: "Gambirigaswewa", divisionalSecretariat: "Nuwaragam Palatha Central" },
  { gnName: "Aluthgama", divisionalSecretariat: "Nuwaragam Palatha Central" },
  { gnName: "Galpottegama", divisionalSecretariat: "Nuwaragam Palatha Central" },
  { gnName: "Maha Ehetuwewa", divisionalSecretariat: "Nuwaragam Palatha Central" },
  { gnName: "Maningamuwa", divisionalSecretariat: "Nuwaragam Palatha Central" },
  { gnName: "Elayapatthuwa", divisionalSecretariat: "Nuwaragam Palatha Central" },
  { gnName: "Diganegama", divisionalSecretariat: "Nuwaragam Palatha Central" },
  { gnName: "Karambewa", divisionalSecretariat: "Nuwaragam Palatha Central" },
  { gnName: "Galkadawela", divisionalSecretariat: "Nuwaragam Palatha Central" },
  { gnName: "Puwarasankulama", divisionalSecretariat: "Nuwaragam Palatha Central" },
  { gnName: "Paniyankadawala", divisionalSecretariat: "Nuwaragam Palatha Central" },
  { gnName: "Parasangaswewa", divisionalSecretariat: "Nuwaragam Palatha Central" },
  { gnName: "Mankadawala", divisionalSecretariat: "Nuwaragam Palatha Central" },
  { gnName: "Saliyapura", divisionalSecretariat: "Nuwaragam Palatha Central" },
  { gnName: "Ashokaramaya", divisionalSecretariat: "Nuwaragam Palatha Central" },
  { gnName: "Perimiyankulama", divisionalSecretariat: "Nuwaragam Palatha Central" },
  { gnName: "Katukeliyawa", divisionalSecretariat: "Nuwaragam Palatha Central" },
  { gnName: "Pusiyankulama", divisionalSecretariat: "Nuwaragam Palatha Central" },
  { gnName: "Maha Mankadawala", divisionalSecretariat: "Nuwaragam Palatha Central" },
  { gnName: "Ilandagahawewa", divisionalSecretariat: "Nuwaragam Palatha Central" },
  { gnName: "Vihara Kallanchiya", divisionalSecretariat: "Nuwaragam Palatha Central" },
  { gnName: "Vihara Palugama", divisionalSecretariat: "Nuwaragam Palatha Central" },
  { gnName: "Devanampiyatissa Pura", divisionalSecretariat: "Nuwaragam Palatha Central" },
  { gnName: "Abayawewa", divisionalSecretariat: "Nuwaragam Palatha Central" },
  { gnName: "Pethispura", divisionalSecretariat: "Nuwaragam Palatha Central" },
  { gnName: "Bandara Puliyankulama", divisionalSecretariat: "Nuwaragam Palatha Central" },
  { gnName: "Jayanthi Gramaya", divisionalSecretariat: "Nuwaragam Palatha Central" },
  { gnName: "Theppankulama", divisionalSecretariat: "Nuwaragam Palatha Central" },
  { gnName: "Thannayamkulama", divisionalSecretariat: "Nuwaragam Palatha Central" },
  { gnName: "Saliya Mawatha", divisionalSecretariat: "Nuwaragam Palatha Central" },
  { gnName: "Scared City", divisionalSecretariat: "Nuwaragam Palatha Central" },
  { gnName: "Tisawewa", divisionalSecretariat: "Nuwaragam Palatha Central" },
  { gnName: "Wessagiriya", divisionalSecretariat: "Nuwaragam Palatha Central" },
  { gnName: "Isurumuniya", divisionalSecretariat: "Nuwaragam Palatha Central" },
  { gnName: "Pandulugama", divisionalSecretariat: "Nuwaragam Palatha Central" },
  { gnName: "Pahalagama", divisionalSecretariat: "Nuwaragam Palatha Central" },
  { gnName: "Maha Bulankulama", divisionalSecretariat: "Nuwaragam Palatha Central" },
  { gnName: "Ulukkulama", divisionalSecretariat: "Nuwaragam Palatha Central" },
  { gnName: "Kolibendawewa", divisionalSecretariat: "Rambewa" },
  { gnName: "Medagama", divisionalSecretariat: "Rambewa" },
  { gnName: "Kadurugasdamana", divisionalSecretariat: "Rambewa" },
  { gnName: "Siyabalagaswewa", divisionalSecretariat: "Rambewa" },
  { gnName: "Katukeliyawa", divisionalSecretariat: "Rambewa" },
  { gnName: "Wahamalgollewa Trak 5", divisionalSecretariat: "Rambewa" },
  { gnName: "Sangilikanandarawa", divisionalSecretariat: "Rambewa" },
  { gnName: "Diviyaudabendawewa", divisionalSecretariat: "Rambewa" },
  { gnName: "Thalgahawewa", divisionalSecretariat: "Rambewa" },
  { gnName: "Galkandegama", divisionalSecretariat: "Rambewa" },
  { gnName: "Balahodawewa", divisionalSecretariat: "Rambewa" },
  { gnName: "Pihimbeyagollewa", divisionalSecretariat: "Rambewa" },
  { gnName: "Galweeragollewa", divisionalSecretariat: "Rambewa" },
  { gnName: "Ambagahawewa", divisionalSecretariat: "Rambewa" },
  { gnName: "Thamarahalmillewa", divisionalSecretariat: "Rambewa" },
  { gnName: "Wewelketiya", divisionalSecretariat: "Rambewa" },
  { gnName: "Ihalakolongaswewa", divisionalSecretariat: "Rambewa" },
  { gnName: "Konakubukwewa", divisionalSecretariat: "Rambewa" },
  { gnName: "Kedewa", divisionalSecretariat: "Rambewa" },
  { gnName: "Kallanchiya", divisionalSecretariat: "Rambewa" },
  { gnName: "Gonewa", divisionalSecretariat: "Rambewa" },
  { gnName: "Ikirigollewa", divisionalSecretariat: "Rambewa" },
  { gnName: "Wahamalgollewa", divisionalSecretariat: "Rambewa" },
  { gnName: "Wahamalgollewa Trak 3", divisionalSecretariat: "Rambewa" },
  { gnName: "Pallankulama", divisionalSecretariat: "Rambewa" },
  { gnName: "Mahawewa", divisionalSecretariat: "Rambewa" },
  { gnName: "Pandukabayapura", divisionalSecretariat: "Rambewa" },
  { gnName: "Katupuliyankulama", divisionalSecretariat: "Rambewa" },
  { gnName: "Sandamalgama", divisionalSecretariat: "Rambewa" },
  { gnName: "Rambewa", divisionalSecretariat: "Rambewa" },
  { gnName: "Nabadagaswewa", divisionalSecretariat: "Rambewa" },
  { gnName: "Mahakandarawa South canal Tank 02", divisionalSecretariat: "Rambewa" },
  { gnName: "Kapirikgama", divisionalSecretariat: "Rambewa" },
  { gnName: "Peenagama", divisionalSecretariat: "Rambewa" },
  { gnName: "Meemalwewa", divisionalSecretariat: "Rambewa" },
  { gnName: "Rotawewa", divisionalSecretariat: "Rambewa" },
  { gnName: "Kudagama", divisionalSecretariat: "Rambewa" },
  { gnName: "Mahakandarawa South Canal Trak 1", divisionalSecretariat: "Rambewa" },
  { gnName: "Kirigallawa", divisionalSecretariat: "Kahatagasdigiliya" },
  { gnName: "Rathmalgahawewa", divisionalSecretariat: "Kahatagasdigiliya" },
  { gnName: "Kudapattiya", divisionalSecretariat: "Kahatagasdigiliya" },
  { gnName: "Maha Kubukwewa", divisionalSecretariat: "Kahatagasdigiliya" },
  { gnName: "Palippothana", divisionalSecretariat: "Kahatagasdigiliya" },
  { gnName: "Gonumeru Wewa", divisionalSecretariat: "Kahatagasdigiliya" },
  { gnName: "Turukkuragama", divisionalSecretariat: "Kahatagasdigiliya" },
  { gnName: "Maha Kiribbewa", divisionalSecretariat: "Kahatagasdigiliya" },
  { gnName: "Maha Galkandegama", divisionalSecretariat: "Kahatagasdigiliya" },
  { gnName: "Dachchihalmillewa", divisionalSecretariat: "Kahatagasdigiliya" },
  { gnName: "Maha Halmillewa", divisionalSecretariat: "Kahatagasdigiliya" },
  { gnName: "Kummukgollewa", divisionalSecretariat: "Kahatagasdigiliya" },
  { gnName: "Pandarellewa", divisionalSecretariat: "Kahatagasdigiliya" },
  { gnName: "Sampath gama", divisionalSecretariat: "Kahatagasdigiliya" },
  { gnName: "Thallaththewa", divisionalSecretariat: "Kahatagasdigiliya" },
  { gnName: "Mahawewa", divisionalSecretariat: "Kahatagasdigiliya" },
  { gnName: "Kahatagasdigiliya East", divisionalSecretariat: "Kahatagasdigiliya" },
  { gnName: "Kahatagasdigiliya West", divisionalSecretariat: "Kahatagasdigiliya" },
  { gnName: "Kokmaduwa", divisionalSecretariat: "Kahatagasdigiliya" },
  { gnName: "Moragahawela", divisionalSecretariat: "Kahatagasdigiliya" },
  { gnName: "Samadigama", divisionalSecretariat: "Kahatagasdigiliya" },
  { gnName: "Mekichchawa", divisionalSecretariat: "Kahatagasdigiliya" },
  { gnName: "Ranpathwila", divisionalSecretariat: "Kahatagasdigiliya" },
  { gnName: "Bethkewa Thulana", divisionalSecretariat: "Kahatagasdigiliya" },
  { gnName: "Maha Messallawa", divisionalSecretariat: "Kahatagasdigiliya" },
  { gnName: "Kohobagaskada", divisionalSecretariat: "Kahatagasdigiliya" },
  { gnName: "Koonwewa", divisionalSecretariat: "Kahatagasdigiliya" },
  { gnName: "Abagahawewa", divisionalSecretariat: "Kahatagasdigiliya" },
  { gnName: "Panwella", divisionalSecretariat: "Kahatagasdigiliya" },
  { gnName: "Mee Kumbukwewa", divisionalSecretariat: "Kahatagasdigiliya" },
  { gnName: "Tikkampothana", divisionalSecretariat: "Kahatagasdigiliya" },
  { gnName: "Punchi Halmillewa", divisionalSecretariat: "Kahatagasdigiliya" },
  { gnName: "Weligollewa", divisionalSecretariat: "Kahatagasdigiliya" },
  { gnName: "Diwulwewa", divisionalSecretariat: "Kahatagasdigiliya" },
  { gnName: "Diganhalmillewa", divisionalSecretariat: "Kahatagasdigiliya" },
  { gnName: "Kelanikawewa", divisionalSecretariat: "Kahatagasdigiliya" },
  { gnName: "Nelugollakada", divisionalSecretariat: "Kahatagasdigiliya" },
  { gnName: "Ellawewa", divisionalSecretariat: "Kahatagasdigiliya" },
  { gnName: "Nekutunu Wewa", divisionalSecretariat: "Kahatagasdigiliya" },
  { gnName: "KanadaraRathmale", divisionalSecretariat: "Kahatagasdigiliya" },
  { gnName: "Wahalkada D2", divisionalSecretariat: "Horowpothana" },
  { gnName: "Wahalkada D 1", divisionalSecretariat: "Horowpothana" },
  { gnName: "Maradanmaduwa", divisionalSecretariat: "Horowpothana" },
  { gnName: "Pahala Divulwewa", divisionalSecretariat: "Horowpothana" },
  { gnName: "Weerasole", divisionalSecretariat: "Horowpothana" },
  { gnName: "Anaolondewa", divisionalSecretariat: "Horowpothana" },
  { gnName: "Kapugollewa", divisionalSecretariat: "Horowpothana" },
  { gnName: "Wagollakada", divisionalSecretariat: "Horowpothana" },
  { gnName: "Dutuwewa", divisionalSecretariat: "Horowpothana" },
  { gnName: "Morawewa", divisionalSecretariat: "Horowpothana" },
  { gnName: "Thawalamhammillewa", divisionalSecretariat: "Horowpothana" },
  { gnName: "Thimbiriathathawala", divisionalSecretariat: "Horowpothana" },
  { gnName: "Nikawewa", divisionalSecretariat: "Horowpothana" },
  { gnName: "Welimuwapothana", divisionalSecretariat: "Horowpothana" },
  { gnName: "Kiulekada", divisionalSecretariat: "Horowpothana" },
  { gnName: "Puhulewewa", divisionalSecretariat: "Horowpothana" },
  { gnName: "Rathmale", divisionalSecretariat: "Horowpothana" },
  { gnName: "Welangahaulpatha", divisionalSecretariat: "Horowpothana" },
  { gnName: "Maradankadawala", divisionalSecretariat: "Horowpothana" },
  { gnName: "Horowpothana", divisionalSecretariat: "Horowpothana" },
  { gnName: "Medawachchiya Handiya", divisionalSecretariat: "Horowpothana" },
  { gnName: "Mukkarawewa", divisionalSecretariat: "Horowpothana" },
  { gnName: "Ihala Angunachchiya", divisionalSecretariat: "Horowpothana" },
  { gnName: "Rasnakawewa", divisionalSecretariat: "Horowpothana" },
  { gnName: "Sinhala Walahaviddawewa", divisionalSecretariat: "Horowpothana" },
  { gnName: "Gammahegewewa", divisionalSecretariat: "Horowpothana" },
  { gnName: "Morakewewa", divisionalSecretariat: "Horowpothana" },
  { gnName: "Nanumillawewa", divisionalSecretariat: "Horowpothana" },
  { gnName: "Thirappankadawala", divisionalSecretariat: "Horowpothana" },
  { gnName: "Parangiyawadiya", divisionalSecretariat: "Horowpothana" },
  { gnName: "Nabadawewa", divisionalSecretariat: "Horowpothana" },
  { gnName: "Puliyankadawala", divisionalSecretariat: "Horowpothana" },
  { gnName: "Wilewewa", divisionalSecretariat: "Horowpothana" },
  { gnName: "Wadigawewa", divisionalSecretariat: "Horowpothana" },
  { gnName: "Kalpe", divisionalSecretariat: "Horowpothana" },
  { gnName: "Dekethipothana", divisionalSecretariat: "Horowpothana" },
  { gnName: "Dematawewa", divisionalSecretariat: "Horowpothana" },
  { gnName: "Diyathithawewa", divisionalSecretariat: "Horowpothana" },
  { gnName: "Konwewa", divisionalSecretariat: "Galenbindunuwewa" },
  { gnName: "Ellawewa", divisionalSecretariat: "Galenbindunuwewa" },
  { gnName: "Katarampura", divisionalSecretariat: "Galenbindunuwewa" },
  { gnName: "Dutuwewa", divisionalSecretariat: "Galenbindunuwewa" },
  { gnName: "Perattupalagama", divisionalSecretariat: "Galenbindunuwewa" },
  { gnName: "Kokawewa", divisionalSecretariat: "Galenbindunuwewa" },
  { gnName: "Dutuwewa Peranigama", divisionalSecretariat: "Galenbindunuwewa" },
  { gnName: "21 Colany East", divisionalSecretariat: "Galenbindunuwewa" },
  { gnName: "21 Colany West", divisionalSecretariat: "Galenbindunuwewa" },
  { gnName: "Ulpathgama", divisionalSecretariat: "Galenbindunuwewa" },
  { gnName: "Upuldeniya", divisionalSecretariat: "Galenbindunuwewa" },
  { gnName: "Himbutugollewa", divisionalSecretariat: "Galenbindunuwewa" },
  { gnName: "Mailagaswewa", divisionalSecretariat: "Galenbindunuwewa" },
  { gnName: "Ihalagama", divisionalSecretariat: "Galenbindunuwewa" },
  { gnName: "Galenbindunuwewa", divisionalSecretariat: "Galenbindunuwewa" },
  { gnName: "Karuwalagaswewa", divisionalSecretariat: "Galenbindunuwewa" },
  { gnName: "Palugollagama", divisionalSecretariat: "Galenbindunuwewa" },
  { gnName: "Aluth Divulwewa", divisionalSecretariat: "Galenbindunuwewa" },
  { gnName: "Gatalawa", divisionalSecretariat: "Galenbindunuwewa" },
  { gnName: "Hurulunikawewa", divisionalSecretariat: "Galenbindunuwewa" },
  { gnName: "Ilukbadayagama", divisionalSecretariat: "Galenbindunuwewa" },
  { gnName: "Kuda Galenbindunuwewa", divisionalSecretariat: "Galenbindunuwewa" },
  { gnName: "Thammennagama", divisionalSecretariat: "Galenbindunuwewa" },
  { gnName: "Siwalakulama", divisionalSecretariat: "Galenbindunuwewa" },
  { gnName: "Gomarankalla", divisionalSecretariat: "Galenbindunuwewa" },
  { gnName: "Hurulunikawewa Yaya 03", divisionalSecretariat: "Galenbindunuwewa" },
  { gnName: "Kumbukwewa", divisionalSecretariat: "Galenbindunuwewa" },
  { gnName: "Janasirigama", divisionalSecretariat: "Galenbindunuwewa" },
  { gnName: "Kurunegala Colony", divisionalSecretariat: "Galenbindunuwewa" },
  { gnName: "Nuwaragam Colony", divisionalSecretariat: "Galenbindunuwewa" },
  { gnName: "Hurulu Jayapura", divisionalSecretariat: "Galenbindunuwewa" },
  { gnName: "Sunanda Mawatha", divisionalSecretariat: "Galenbindunuwewa" },
  { gnName: "Galwaduwagama", divisionalSecretariat: "Galenbindunuwewa" },
  { gnName: "Muriyakadawala", divisionalSecretariat: "Galenbindunuwewa" },
  { gnName: "Ihala Galkulama", divisionalSecretariat: "Galenbindunuwewa" },
  { gnName: "Hurulumeegahapattiya", divisionalSecretariat: "Galenbindunuwewa" },
  { gnName: "Nuwaraeliya Colany", divisionalSecretariat: "Galenbindunuwewa" },
  { gnName: "Pandikaramaduwa", divisionalSecretariat: "Galenbindunuwewa" },
  { gnName: "Yakalla", divisionalSecretariat: "Galenbindunuwewa" },
  { gnName: "Manankattiya", divisionalSecretariat: "Galenbindunuwewa" },
  { gnName: "Wannankulama", divisionalSecretariat: "Galenbindunuwewa" },
  { gnName: "Ukkulankulama", divisionalSecretariat: "Mihinthale" },
  { gnName: "Mahakanadarawa - yaya 03", divisionalSecretariat: "Mihinthale" },
  { gnName: "Mahakandarawa - Yaya 02", divisionalSecretariat: "Mihinthale" },
  { gnName: "Mahakanadarawa Yaya 01", divisionalSecretariat: "Mihinthale" },
  { gnName: "Maradankulama", divisionalSecretariat: "Mihinthale" },
  { gnName: "Doramadalawa", divisionalSecretariat: "Mihinthale" },
  { gnName: "Kunchikulam", divisionalSecretariat: "Mihinthale" },
  { gnName: "Henawaththa", divisionalSecretariat: "Mihinthale" },
  { gnName: "Nuwarawewa", divisionalSecretariat: "Mihinthale" },
  { gnName: "Kurundankulam", divisionalSecretariat: "Mihinthale" },
  { gnName: "Kannattiya", divisionalSecretariat: "Mihinthale" },
  { gnName: "Mihintale", divisionalSecretariat: "Mihinthale" },
  { gnName: "Ruwangama", divisionalSecretariat: "Mihinthale" },
  { gnName: "Namalwewa", divisionalSecretariat: "Mihinthale" },
  { gnName: "Bogahayaya", divisionalSecretariat: "Mihinthale" },
  { gnName: "Pothana", divisionalSecretariat: "Mihinthale" },
  { gnName: "Seeppukulama", divisionalSecretariat: "Mihinthale" },
  { gnName: "Thammennawa", divisionalSecretariat: "Mihinthale" },
  { gnName: "Kasamaduwa", divisionalSecretariat: "Mihinthale" },
  { gnName: "Katukeliyawa", divisionalSecretariat: "Mihinthale" },
  { gnName: "Kattambuwagama", divisionalSecretariat: "Mihinthale" },
  { gnName: "Kahapathwilagama", divisionalSecretariat: "Mihinthale" },
  { gnName: "Ihalagama", divisionalSecretariat: "Mihinthale" },
  { gnName: "Maradankalla", divisionalSecretariat: "Mihinthale" },
  { gnName: "Wellaragama", divisionalSecretariat: "Mihinthale" },
  { gnName: "Nuwarawewa", divisionalSecretariat: "Nuwaragam Palatha East" },
  { gnName: "Stage (1) part (1)", divisionalSecretariat: "Nuwaragam Palatha East" },
  { gnName: "Maha Kalaththawa", divisionalSecretariat: "Nuwaragam Palatha East" },
  { gnName: "Thariyankulama", divisionalSecretariat: "Nuwaragam Palatha East" },
  { gnName: "Nelunkanniya", divisionalSecretariat: "Nuwaragam Palatha East" },
  { gnName: "Kuda Nelumkulama", divisionalSecretariat: "Nuwaragam Palatha East" },
  { gnName: "Keerikkulama", divisionalSecretariat: "Nuwaragam Palatha East" },
  { gnName: "Thammannapura", divisionalSecretariat: "Nuwaragam Palatha East" },
  { gnName: "Vannithammannawa", divisionalSecretariat: "Nuwaragam Palatha East" },
  { gnName: "Thammannakulama", divisionalSecretariat: "Nuwaragam Palatha East" },
  { gnName: "Stage (1) part (II)", divisionalSecretariat: "Nuwaragam Palatha East" },
  { gnName: "Stage (II) part (III).", divisionalSecretariat: "Nuwaragam Palatha East" },
  { gnName: "Stage (II) part (II)", divisionalSecretariat: "Nuwaragam Palatha East" },
  { gnName: "Pothanegama", divisionalSecretariat: "Nuwaragam Palatha East" },
  { gnName: "Stage (III) part (III)", divisionalSecretariat: "Nuwaragam Palatha East" },
  { gnName: "Stage (II) part (1)", divisionalSecretariat: "Nuwaragam Palatha East" },
  { gnName: "Stage (II) part (IV)", divisionalSecretariat: "Nuwaragam Palatha East" },
  { gnName: "Vanniyankulama (IV)", divisionalSecretariat: "Nuwaragam Palatha East" },
  { gnName: "Vanniyankulama (V)", divisionalSecretariat: "Nuwaragam Palatha East" },
  { gnName: "Vanniyankulama (VI)", divisionalSecretariat: "Nuwaragam Palatha East" },
  { gnName: "Ghanikulama", divisionalSecretariat: "Nuwaragam Palatha East" },
  { gnName: "Kawarakkulama", divisionalSecretariat: "Nuwaragam Palatha East" },
  { gnName: "MahaPaladikulama", divisionalSecretariat: "Nuwaragam Palatha East" },
  { gnName: "Stage(III) part (1)", divisionalSecretariat: "Nuwaragam Palatha East" },
  { gnName: "Stage(III) part (II)", divisionalSecretariat: "Nuwaragam Palatha East" },
  { gnName: "Vanniyankulama (  ", divisionalSecretariat: "Nuwaragam Palatha East" },
  { gnName: "Vanniyankulama (1)", divisionalSecretariat: "Nuwaragam Palatha East" },
  { gnName: "Vanniyankulama (II ", divisionalSecretariat: "Nuwaragam Palatha East" },
  { gnName: "Sucharithagama", divisionalSecretariat: "Nuwaragam Palatha East" },
  { gnName: "Kibulakada", divisionalSecretariat: "Nachchadoowa" },
  { gnName: "Srawasthipura", divisionalSecretariat: "Nachchadoowa" },
  { gnName: "Kuda Nelubewa", divisionalSecretariat: "Nachchadoowa" },
  { gnName: "Srawasthiwaththa", divisionalSecretariat: "Nachchadoowa" },
  { gnName: "Aluthwewa", divisionalSecretariat: "Nachchadoowa" },
  { gnName: "Amane", divisionalSecretariat: "Nachchadoowa" },
  { gnName: "Maha Nelubewa", divisionalSecretariat: "Nachchadoowa" },
  { gnName: "Diwulwewa", divisionalSecretariat: "Nachchadoowa" },
  { gnName: "Hidogama", divisionalSecretariat: "Nachchadoowa" },
  { gnName: "Pawakkulama", divisionalSecretariat: "Nachchadoowa" },
  { gnName: "Uthuru Kaluwila", divisionalSecretariat: "Nachchadoowa" },
  { gnName: "Madawalagama", divisionalSecretariat: "Nachchadoowa" },
  { gnName: "Nachchaduwa", divisionalSecretariat: "Nachchadoowa" },
  { gnName: "Nachchaduwa New Town", divisionalSecretariat: "Nachchadoowa" },
  { gnName: "Palayakulama", divisionalSecretariat: "Nachchadoowa" },
  { gnName: "Suhadagama", divisionalSecretariat: "Nachchadoowa" },
  { gnName: "Thuruwila", divisionalSecretariat: "Nachchadoowa" },
  { gnName: "Kaluarachchiyagama", divisionalSecretariat: "Nachchadoowa" },
  { gnName: "Pahalawewa", divisionalSecretariat: "Nachchadoowa" },
  { gnName: "Kukulkatuwa", divisionalSecretariat: "Nochchiyagama" },
  { gnName: "Ittikulama", divisionalSecretariat: "Nochchiyagama" },
  { gnName: "Ranorawa", divisionalSecretariat: "Nochchiyagama" },
  { gnName: "Mahalindawewa", divisionalSecretariat: "Nochchiyagama" },
  { gnName: "Bogahawewa", divisionalSecretariat: "Nochchiyagama" },
  { gnName: "Ambagahawewa", divisionalSecretariat: "Nochchiyagama" },
  { gnName: "Ehetuwagama", divisionalSecretariat: "Nochchiyagama" },
  { gnName: "Thalgaswewa", divisionalSecretariat: "Nochchiyagama" },
  { gnName: "Hunuvilagama", divisionalSecretariat: "Nochchiyagama" },
  { gnName: "Horuvila", divisionalSecretariat: "Nochchiyagama" },
  { gnName: "Lindawewa", divisionalSecretariat: "Nochchiyagama" },
  { gnName: "Kusumpura", divisionalSecretariat: "Nochchiyagama" },
  { gnName: "Mudithagama", divisionalSecretariat: "Nochchiyagama" },
  { gnName: "Ralapanawagama", divisionalSecretariat: "Nochchiyagama" },
  { gnName: "Adampane", divisionalSecretariat: "Nochchiyagama" },
  { gnName: "Andarawewa", divisionalSecretariat: "Nochchiyagama" },
  { gnName: "Ralapanawa Jnapadaya", divisionalSecretariat: "Nochchiyagama" },
  { gnName: "Nochchiyagama", divisionalSecretariat: "Nochchiyagama" },
  { gnName: "Dunudambuwewa", divisionalSecretariat: "Nochchiyagama" },
  { gnName: "Thimbiriwewa", divisionalSecretariat: "Nochchiyagama" },
  { gnName: "Katupathwewa", divisionalSecretariat: "Nochchiyagama" },
  { gnName: "Pahala Maragahawewa", divisionalSecretariat: "Nochchiyagama" },
  { gnName: "Nelawagama", divisionalSecretariat: "Nochchiyagama" },
  { gnName: "Pahala Halmillewa", divisionalSecretariat: "Nochchiyagama" },
  { gnName: "Halmillakulama", divisionalSecretariat: "Nochchiyagama" },
  { gnName: "Dunupothagama", divisionalSecretariat: "Nochchiyagama" },
  { gnName: "Dombawalagama", divisionalSecretariat: "Nochchiyagama" },
  { gnName: "Pahamunegama", divisionalSecretariat: "Nochchiyagama" },
  { gnName: "Nawakkulama", divisionalSecretariat: "Nochchiyagama" },
  { gnName: "Galadiulwewa", divisionalSecretariat: "Nochchiyagama" },
  { gnName: "Jayagama", divisionalSecretariat: "Nochchiyagama" },
  { gnName: "Amunukole", divisionalSecretariat: "Nochchiyagama" },
  { gnName: "Mihiripura", divisionalSecretariat: "Nochchiyagama" },
  { gnName: "Pahala Kedithokkuwa", divisionalSecretariat: "Nochchiyagama" },
  { gnName: "Rankethgama", divisionalSecretariat: "Nochchiyagama" },
  { gnName: "Ottappuwa", divisionalSecretariat: "Nochchiyagama" },
  { gnName: "Track 13-18", divisionalSecretariat: "Rajanganaya" },
  { gnName: "Track 16-17", divisionalSecretariat: "Rajanganaya" },
  { gnName: "Veheragala", divisionalSecretariat: "Rajanganaya" },
  { gnName: "Track 12", divisionalSecretariat: "Rajanganaya" },
  { gnName: "Thulana Track 9-10", divisionalSecretariat: "Rajanganaya" },
  { gnName: "Track 11", divisionalSecretariat: "Rajanganaya" },
  { gnName: "Track 15", divisionalSecretariat: "Rajanganaya" },
  { gnName: "Gemunupura", divisionalSecretariat: "Rajanganaya" },
  { gnName: "Track 07", divisionalSecretariat: "Rajanganaya" },
  { gnName: "Thumbullegama", divisionalSecretariat: "Rajanganaya" },
  { gnName: "Randenigama", divisionalSecretariat: "Rajanganaya" },
  { gnName: "Track 4", divisionalSecretariat: "Rajanganaya" },
  { gnName: "Track 3", divisionalSecretariat: "Rajanganaya" },
  { gnName: "Naigala", divisionalSecretariat: "Rajanganaya" },
  { gnName: "Thissapura", divisionalSecretariat: "Rajanganaya" },
  { gnName: "Maha Thibrikalla", divisionalSecretariat: "Rajanganaya" },
  { gnName: "Angamuwa", divisionalSecretariat: "Rajanganaya" },
  { gnName: "4 1/2 Kanuwa", divisionalSecretariat: "Rajanganaya" },
  { gnName: "Sirimapura", divisionalSecretariat: "Rajanganaya" },
  { gnName: "Pantiyawa", divisionalSecretariat: "Rajanganaya" },
  { gnName: "Kalundegama", divisionalSecretariat: "Rajanganaya" },
  { gnName: "Koongollewa", divisionalSecretariat: "Thambuttegama" },
  { gnName: "Kalegama", divisionalSecretariat: "Thambuttegama" },
  { gnName: "Pahalagama", divisionalSecretariat: "Thambuttegama" },
  { gnName: "Solama", divisionalSecretariat: "Thambuttegama" },
  { gnName: "Maha Bellankadawala", divisionalSecretariat: "Thambuttegama" },
  { gnName: "Eriyagama", divisionalSecretariat: "Thambuttegama" },
  { gnName: "Delnegama", divisionalSecretariat: "Thambuttegama" },
  { gnName: "Kuda Bellankada", divisionalSecretariat: "Thambuttegama" },
  { gnName: "Koonwewa", divisionalSecretariat: "Thambuttegama" },
  { gnName: "Jayasirigama", divisionalSecretariat: "Thambuttegama" },
  { gnName: "Lunuwewa", divisionalSecretariat: "Thambuttegama" },
  { gnName: "Veheragala", divisionalSecretariat: "Thambuttegama" },
  { gnName: "Thammennagama", divisionalSecretariat: "Thambuttegama" },
  { gnName: "Nallachiya", divisionalSecretariat: "Thambuttegama" },
  { gnName: "Galviharawewa", divisionalSecretariat: "Thambuttegama" },
  { gnName: "Thelhiriyawa", divisionalSecretariat: "Thambuttegama" },
  { gnName: "Ikiriwewa", divisionalSecretariat: "Thambuttegama" },
  { gnName: "Musalpitiya", divisionalSecretariat: "Thambuttegama" },
  { gnName: "Thispanepura", divisionalSecretariat: "Thambuttegama" },
  { gnName: "Makulewa", divisionalSecretariat: "Thambuttegama" },
  { gnName: "Thammennawa", divisionalSecretariat: "Thambuttegama" },
  { gnName: "Mudungoda", divisionalSecretariat: "Thambuttegama" },
  { gnName: "Helambawewa", divisionalSecretariat: "Thambuttegama" },
  { gnName: "Hureegaswewa", divisionalSecretariat: "Thambuttegama" },
  { gnName: "Weliyawa", divisionalSecretariat: "Thambuttegama" },
  { gnName: "418 Thambuttegama", divisionalSecretariat: "Thambuttegama" },
  { gnName: "Daladapura", divisionalSecretariat: "Thalawa" },
  { gnName: "Pahala Talawa", divisionalSecretariat: "Thalawa" },
  { gnName: "Moragoda", divisionalSecretariat: "Thalawa" },
  { gnName: "Kumbukgahawewa", divisionalSecretariat: "Thalawa" },
  { gnName: "Nawa Hanguranketha", divisionalSecretariat: "Thalawa" },
  { gnName: "Hirigollegama", divisionalSecretariat: "Thalawa" },
  { gnName: "Karagahawewa", divisionalSecretariat: "Thalawa" },
  { gnName: "Ihala Thalawa", divisionalSecretariat: "Thalawa" },
  { gnName: "Hinguruwewa", divisionalSecretariat: "Thalawa" },
  { gnName: "Korakahawewa", divisionalSecretariat: "Thalawa" },
  { gnName: "Kurunduwewa", divisionalSecretariat: "Thalawa" },
  { gnName: "Meegassegama", divisionalSecretariat: "Thalawa" },
  { gnName: "Kiralogama", divisionalSecretariat: "Thalawa" },
  { gnName: "Kadurugaswewa", divisionalSecretariat: "Thalawa" },
  { gnName: "Palugaswewa", divisionalSecretariat: "Thalawa" },
  { gnName: "Ketakale", divisionalSecretariat: "Thalawa" },
  { gnName: "Rajjallegama", divisionalSecretariat: "Thalawa" },
  { gnName: "Eliyadivulwewa", divisionalSecretariat: "Thalawa" },
  { gnName: "Ihala Siyambalewa", divisionalSecretariat: "Thalawa" },
  { gnName: "Eppawala", divisionalSecretariat: "Thalawa" },
  { gnName: "Mawathawewa", divisionalSecretariat: "Thalawa" },
  { gnName: "Nallamudawa", divisionalSecretariat: "Thalawa" },
  { gnName: "Medagama", divisionalSecretariat: "Thalawa" },
  { gnName: "Kiriamunakole", divisionalSecretariat: "Thalawa" },
  { gnName: "Kadigawa", divisionalSecretariat: "Thalawa" },
  { gnName: "Mediyawa", divisionalSecretariat: "Thalawa" },
  { gnName: "Katiyawa Track 02", divisionalSecretariat: "Thalawa" },
  { gnName: "Galwaduwagama", divisionalSecretariat: "Thalawa" },
  { gnName: "Ihala Halmillewa", divisionalSecretariat: "Thalawa" },
  { gnName: "Adhiranigama", divisionalSecretariat: "Thalawa" },
  { gnName: "Katiyawa Track 10", divisionalSecretariat: "Thalawa" },
  { gnName: "Katiyawa Track 09", divisionalSecretariat: "Thalawa" },
  { gnName: "Katiyawa Track 01", divisionalSecretariat: "Thalawa" },
  { gnName: "Edagala", divisionalSecretariat: "Thalawa" },
  { gnName: "Kelesiyambalewa", divisionalSecretariat: "Thalawa" },
  { gnName: "Galmaduwa", divisionalSecretariat: "Thalawa" },
  { gnName: "Ihalagama", divisionalSecretariat: "Thalawa" },
  { gnName: "Keledivulwewa", divisionalSecretariat: "Thalawa" },
  { gnName: "Katiyawa Track 06", divisionalSecretariat: "Thalawa" },
  { gnName: "Karuwalagaswewa", divisionalSecretariat: "Thirappane" },
  { gnName: "Galkulama", divisionalSecretariat: "Thirappane" },
  { gnName: "Gnanikkulama", divisionalSecretariat: "Thirappane" },
  { gnName: "Perimiyankulama", divisionalSecretariat: "Thirappane" },
  { gnName: "Wannankulama", divisionalSecretariat: "Thirappane" },
  { gnName: "Uttimaduwa", divisionalSecretariat: "Thirappane" },
  { gnName: "Dematawewa", divisionalSecretariat: "Thirappane" },
  { gnName: "Pairimaduwa", divisionalSecretariat: "Thirappane" },
  { gnName: "Kuttikulama", divisionalSecretariat: "Thirappane" },
  { gnName: "Puliyankulama", divisionalSecretariat: "Thirappane" },
  { gnName: "Mawathawewa", divisionalSecretariat: "Thirappane" },
  { gnName: "Periyakulama", divisionalSecretariat: "Thirappane" },
  { gnName: "Ethungama South", divisionalSecretariat: "Thirappane" },
  { gnName: "Meewellewa", divisionalSecretariat: "Thirappane" },
  { gnName: "Ethungama North", divisionalSecretariat: "Thirappane" },
  { gnName: "Aluthpunchikulama", divisionalSecretariat: "Thirappane" },
  { gnName: "Wannammaduwa", divisionalSecretariat: "Thirappane" },
  { gnName: "Tirappane Kadaweediya", divisionalSecretariat: "Thirappane" },
  { gnName: "Thirappane Gama", divisionalSecretariat: "Thirappane" },
  { gnName: "Sembukulama", divisionalSecretariat: "Thirappane" },
  { gnName: "Wellamudawa", divisionalSecretariat: "Thirappane" },
  { gnName: "Selesthimaduwa", divisionalSecretariat: "Thirappane" },
  { gnName: "Indigahawewa", divisionalSecretariat: "Thirappane" },
  { gnName: "Paindikulama", divisionalSecretariat: "Thirappane" },
  { gnName: "Walagambahuwa", divisionalSecretariat: "Thirappane" },
  { gnName: "Mahakanumulla.", divisionalSecretariat: "Thirappane" },
  { gnName: "Alisthana", divisionalSecretariat: "Thirappane" },
  { gnName: "Dayagama", divisionalSecretariat: "Thirappane" },
  { gnName: "Wanamal Uyana", divisionalSecretariat: "Thirappane" },
  { gnName: "Manakkulama", divisionalSecretariat: "Thirappane" },
  { gnName: "Pethirambewa", divisionalSecretariat: "Thirappane" },
  { gnName: "Kattamurichchana", divisionalSecretariat: "Thirappane" },
  { gnName: "Kandupagama", divisionalSecretariat: "Thirappane" },
  { gnName: "Labunoruwa", divisionalSecretariat: "Thirappane" },
  { gnName: "Pahala Ambathale", divisionalSecretariat: "Thirappane" },
  { gnName: "Ihala Ambathale", divisionalSecretariat: "Thirappane" },
  { gnName: "Alagollewa", divisionalSecretariat: "Thirappane" },
  { gnName: "Muriyakadawala", divisionalSecretariat: "Thirappane" },
  { gnName: "Amunnichchiya", divisionalSecretariat: "Thirappane" },
  { gnName: "Sandapagama", divisionalSecretariat: "Thirappane" },
  { gnName: "Uththupitiya", divisionalSecretariat: "Thirappane" },
  { gnName: "Nawakkulama", divisionalSecretariat: "Kekirawa" },
  { gnName: "Moragoda", divisionalSecretariat: "Kekirawa" },
  { gnName: "Mahadiwulwewa", divisionalSecretariat: "Kekirawa" },
  { gnName: "Keeriyagaswewa", divisionalSecretariat: "Kekirawa" },
  { gnName: "Ihala Puliyankulama", divisionalSecretariat: "Kekirawa" },
  { gnName: "Kele-Puliyankulama", divisionalSecretariat: "Kekirawa" },
  { gnName: "Maradankadawela", divisionalSecretariat: "Kekirawa" },
  { gnName: "Thoruwewa", divisionalSecretariat: "Kekirawa" },
  { gnName: "Maminiyawa", divisionalSecretariat: "Kekirawa" },
  { gnName: "Maminiya Rambewa", divisionalSecretariat: "Kekirawa" },
  { gnName: "Ganewalpola", divisionalSecretariat: "Kekirawa" },
  { gnName: "Heenukkiriyawa", divisionalSecretariat: "Kekirawa" },
  { gnName: "Ebulgaswewa", divisionalSecretariat: "Kekirawa" },
  { gnName: "Olukaranda", divisionalSecretariat: "Kekirawa" },
  { gnName: "Kollankuttigama", divisionalSecretariat: "Kekirawa" },
  { gnName: "Mudaperumagama", divisionalSecretariat: "Kekirawa" },
  { gnName: "Ihalagama", divisionalSecretariat: "Kekirawa" },
  { gnName: "Shasthrawelliya", divisionalSecretariat: "Kekirawa" },
  { gnName: "Railway Town", divisionalSecretariat: "Kekirawa" },
  { gnName: "Maradankadawala Road", divisionalSecretariat: "Kekirawa" },
  { gnName: "Maldenipura", divisionalSecretariat: "Kekirawa" },
  { gnName: "Mankadawala", divisionalSecretariat: "Kekirawa" },
  { gnName: "Medawewa", divisionalSecretariat: "Kekirawa" },
  { gnName: "Pothanegama", divisionalSecretariat: "Kekirawa" },
  { gnName: "Kuda Kekirawa", divisionalSecretariat: "Kekirawa" },
  { gnName: "Kekirawa Town", divisionalSecretariat: "Kekirawa" },
  { gnName: "Malawa", divisionalSecretariat: "Kekirawa" },
  { gnName: "Neekiniyawa", divisionalSecretariat: "Kekirawa" },
  { gnName: "Mailagaswewa", divisionalSecretariat: "Kekirawa" },
  { gnName: "Karukkankulama", divisionalSecretariat: "Kekirawa" },
  { gnName: "Olombewa", divisionalSecretariat: "Kekirawa" },
  { gnName: "Maha Kekirawa", divisionalSecretariat: "Kekirawa" },
  { gnName: "Kumbukwewa", divisionalSecretariat: "Kekirawa" },
  { gnName: "Rathmallewa.", divisionalSecretariat: "Kekirawa" },
  { gnName: "Medagama", divisionalSecretariat: "Kekirawa" },
  { gnName: "Korasagalla", divisionalSecretariat: "Kekirawa" },
  { gnName: "Unagollewa", divisionalSecretariat: "Kekirawa" },
  { gnName: "Horapola", divisionalSecretariat: "Kekirawa" },
  { gnName: "Dambewatana", divisionalSecretariat: "Kekirawa" },
  { gnName: "Undurawa", divisionalSecretariat: "Kekirawa" },
  { gnName: "Nidigama", divisionalSecretariat: "Kekirawa" },
  { gnName: "Maha Elagamuwa", divisionalSecretariat: "Kekirawa" },
  { gnName: "Pallehigura", divisionalSecretariat: "Kekirawa" },
  { gnName: "Nelbagama", divisionalSecretariat: "Kekirawa" },
  { gnName: "Murungahitikanda", divisionalSecretariat: "Kekirawa" },
  { gnName: "Baravila", divisionalSecretariat: "Kekirawa" },
  { gnName: "Bandarapathana", divisionalSecretariat: "Kekirawa" },
  { gnName: "Kotagala", divisionalSecretariat: "Kekirawa" },
  { gnName: "Madatugama", divisionalSecretariat: "Kekirawa" },
  { gnName: "Dunumadalawa", divisionalSecretariat: "Kekirawa" },
  { gnName: "Kandalama West", divisionalSecretariat: "Kekirawa" },
  { gnName: "Kithulhitiyawa", divisionalSecretariat: "Kekirawa" },
  { gnName: "Kandalama East", divisionalSecretariat: "Kekirawa" },
  { gnName: "Mithreegama", divisionalSecretariat: "Palugaswewa" },
  { gnName: "Maharabawewa", divisionalSecretariat: "Palugaswewa" },
  { gnName: "Madawala", divisionalSecretariat: "Palugaswewa" },
  { gnName: "Eppawala", divisionalSecretariat: "Palugaswewa" },
  { gnName: "Galapitagala", divisionalSecretariat: "Palugaswewa" },
  { gnName: "Kumbukwewa", divisionalSecretariat: "Palugaswewa" },
  { gnName: "Senadiriyagama", divisionalSecretariat: "Palugaswewa" },
  { gnName: "Horovila", divisionalSecretariat: "Palugaswewa" },
  { gnName: "Palugaswewa", divisionalSecretariat: "Palugaswewa" },
  { gnName: "Kudarambawewa", divisionalSecretariat: "Palugaswewa" },
  { gnName: "Habarana", divisionalSecretariat: "Palugaswewa" },
  { gnName: "Demunnewa", divisionalSecretariat: "Palugaswewa" },
  { gnName: "Kelewa", divisionalSecretariat: "Palugaswewa" },
  { gnName: "Vayaulpatha", divisionalSecretariat: "Palugaswewa" },
  { gnName: "Hiriwadunna", divisionalSecretariat: "Palugaswewa" },
  { gnName: "Kashyapagama", divisionalSecretariat: "Palugaswewa" },
  { gnName: "Dikwewa-Senapura", divisionalSecretariat: "Ipalogama" },
  { gnName: "Galagedara Gama", divisionalSecretariat: "Ipalogama" },
  { gnName: "Senapura Gama", divisionalSecretariat: "Ipalogama" },
  { gnName: "Mahailuppallama", divisionalSecretariat: "Ipalogama" },
  { gnName: "Gonapathirawa", divisionalSecretariat: "Ipalogama" },
  { gnName: "Sangattewa", divisionalSecretariat: "Ipalogama" },
  { gnName: "Kadiyangalla", divisionalSecretariat: "Ipalogama" },
  { gnName: "Ipalogama", divisionalSecretariat: "Ipalogama" },
  { gnName: "Manewa", divisionalSecretariat: "Ipalogama" },
  { gnName: "Heenukwe Gama", divisionalSecretariat: "Ipalogama" },
  { gnName: "Dampelassagama", divisionalSecretariat: "Ipalogama" },
  { gnName: "Ihala Kagama", divisionalSecretariat: "Ipalogama" },
  { gnName: "Kunchikulama", divisionalSecretariat: "Ipalogama" },
  { gnName: "Hiripitiyagama", divisionalSecretariat: "Ipalogama" },
  { gnName: "Aswedduma", divisionalSecretariat: "Ipalogama" },
  { gnName: "Ganthiriya Gama", divisionalSecretariat: "Ipalogama" },
  { gnName: "Galwanguwa", divisionalSecretariat: "Ipalogama" },
  { gnName: "Wedinigama", divisionalSecretariat: "Ipalogama" },
  { gnName: "Narangallegama", divisionalSecretariat: "Ipalogama" },
  { gnName: "Kallanchiyagama", divisionalSecretariat: "Ipalogama" },
  { gnName: "Aluth Dambewatana", divisionalSecretariat: "Ipalogama" },
  { gnName: "R.B. 2 Ela Kagama", divisionalSecretariat: "Ipalogama" },
  { gnName: "2 Ela Kagama", divisionalSecretariat: "Ipalogama" },
  { gnName: "Akkara 500", divisionalSecretariat: "Ipalogama" },
  { gnName: "Amunawetiya", divisionalSecretariat: "Ipalogama" },
  { gnName: "Puliyankulama", divisionalSecretariat: "Ipalogama" },
  { gnName: "Vijithapura", divisionalSecretariat: "Ipalogama" },
  { gnName: "Amanakkattuwa", divisionalSecretariat: "Ipalogama" },
  { gnName: "Kalawewa", divisionalSecretariat: "Ipalogama" },
  { gnName: "Kusalanagama", divisionalSecretariat: "Ipalogama" },
  { gnName: "Palugaswewa Farm", divisionalSecretariat: "Ipalogama" },
  { gnName: "Walawwegama", divisionalSecretariat: "Ipalogama" },
  { gnName: "Namalgamuwa", divisionalSecretariat: "Galnewa" },
  { gnName: "Obadayagama", divisionalSecretariat: "Galnewa" },
  { gnName: "Otunupalandigama", divisionalSecretariat: "Galnewa" },
  { gnName: "Karuwalagaswewa", divisionalSecretariat: "Galnewa" },
  { gnName: "Usgala Halmillawewa", divisionalSecretariat: "Galnewa" },
  { gnName: "Helabodugama", divisionalSecretariat: "Galnewa" },
  { gnName: "Kaththaragama", divisionalSecretariat: "Galnewa" },
  { gnName: "Bulnewa", divisionalSecretariat: "Galnewa" },
  { gnName: "Thoranegama", divisionalSecretariat: "Galnewa" },
  { gnName: "Midellewa", divisionalSecretariat: "Galnewa" },
  { gnName: "Ihala Kalankuttiya", divisionalSecretariat: "Galnewa" },
  { gnName: "Pahala Kalankuttiya", divisionalSecretariat: "Galnewa" },
  { gnName: "Siyambalewa", divisionalSecretariat: "Galnewa" },
  { gnName: "Lolugaswewa", divisionalSecretariat: "Galnewa" },
  { gnName: "Pitiye Yaya", divisionalSecretariat: "Galnewa" },
  { gnName: "Galnewagama", divisionalSecretariat: "Galnewa" },
  { gnName: "Galnewa Town", divisionalSecretariat: "Galnewa" },
  { gnName: "Malbaligala", divisionalSecretariat: "Galnewa" },
  { gnName: "Handungama", divisionalSecretariat: "Galnewa" },
  { gnName: "Musnawa", divisionalSecretariat: "Galnewa" },
  { gnName: "Kala-Medawachchiya", divisionalSecretariat: "Galnewa" },
  { gnName: "Kumbukwewa", divisionalSecretariat: "Galnewa" },
  { gnName: "Kallanchiya", divisionalSecretariat: "Galnewa" },
  { gnName: "Negama", divisionalSecretariat: "Galnewa" },
  { gnName: "Werunkulama", divisionalSecretariat: "Galnewa" },
  { gnName: "Walaswewa", divisionalSecretariat: "Galnewa" },
  { gnName: "Kandegama", divisionalSecretariat: "Galnewa" },
  { gnName: "Kandulegama", divisionalSecretariat: "Galnewa" },
  { gnName: "Kandulugamuwa", divisionalSecretariat: "Galnewa" },
  { gnName: "Dakunu Siyambalagamuwa", divisionalSecretariat: "Galnewa" },
  { gnName: "Nelliyagama", divisionalSecretariat: "Palagala" },
  { gnName: "Balaluwewa 2", divisionalSecretariat: "Palagala" },
  { gnName: "Balaluwewa", divisionalSecretariat: "Palagala" },
  { gnName: "Pahalagama", divisionalSecretariat: "Palagala" },
  { gnName: "Karawilagala", divisionalSecretariat: "Palagala" },
  { gnName: "Gamsabhahalmillawewa", divisionalSecretariat: "Palagala" },
  { gnName: "Gonadeniyagama", divisionalSecretariat: "Palagala" },
  { gnName: "Meewewa", divisionalSecretariat: "Palagala" },
  { gnName: "Ambagaswewa", divisionalSecretariat: "Palagala" },
  { gnName: "Warnbatuwewa", divisionalSecretariat: "Palagala" },
  { gnName: "Hinguruwewa", divisionalSecretariat: "Palagala" },
  { gnName: "Kirindiwettha", divisionalSecretariat: "Palagala" },
  { gnName: "Aluth Galkiriyagama", divisionalSecretariat: "Palagala" },
  { gnName: "Daniyagama", divisionalSecretariat: "Palagala" },
  { gnName: "Undurawa Halmillawewa", divisionalSecretariat: "Palagala" },
  { gnName: "Katukelliyawa", divisionalSecretariat: "Palagala" },
  { gnName: "Aluth Kadadugama", divisionalSecretariat: "Palagala" },
  { gnName: "Ranawa", divisionalSecretariat: "Palagala" },
  { gnName: "Higuruwelpitiya", divisionalSecretariat: "Palagala" },
  { gnName: "Anakatawewa", divisionalSecretariat: "Palagala" },
  { gnName: "Giranegama", divisionalSecretariat: "Palagala" },
  { gnName: "Dammbuluhalmillawewa", divisionalSecretariat: "Palagala" },
  { gnName: "Narangaswewa", divisionalSecretariat: "Palagala" },
  { gnName: "Ulpathagama", divisionalSecretariat: "Palagala" },
  { gnName: "Ellawewa", divisionalSecretariat: "Palagala" },
  { gnName: "Andiyagala", divisionalSecretariat: "Palagala" },
  { gnName: "Maneruwa", divisionalSecretariat: "Palagala" },
  { gnName: "Ipulwehera", divisionalSecretariat: "Palagala" },
  { gnName: "Gambirigaswewa", divisionalSecretariat: "Palagala" },
  { gnName: "Parawahagama", divisionalSecretariat: "Palagala" },
  { gnName: "Kalugala", divisionalSecretariat: "Palagala" },
  { gnName: "Pelbediyawa", divisionalSecretariat: "Palagala" },
  { gnName: "Morettegama", divisionalSecretariat: "Palagala" },
  { gnName: "Dematagollagama", divisionalSecretariat: "Palagala" },
  { gnName: "Budugehinna", divisionalSecretariat: "Palagala" },
];

// Helper function to get unique divisional secretariats
export function getDivisionalSecretariats(): string[] {
  const secretariats = new Set<string>();
  gnList.forEach((item) => secretariats.add(item.divisionalSecretariat));
  return Array.from(secretariats).sort();
}

// Helper function to get GN names for a specific divisional secretariat
export function getGNNamesBySecretariat(secretariat: string): string[] {
  return gnList
    .filter((item) => item.divisionalSecretariat === secretariat)
    .map((item) => item.gnName)
    .sort();
}

// Backward compatibility - export the old array format
export const gnEnglishNames: string[] = gnList.map((item) => item.gnName);
